### PR TITLE
Unicode 7 & 8 emoji & generator for future updates

### PR DESCRIPTION
**Pull request by louiszuckerman**
To support future Unicode updates and additional related words, I have...
- Introduced a script, generate.rb, which generates symbol & word list files, and images, from the official emoji list from unicode.org
- Replaced ruby hash files with JSON files

### CODE REVIEW

**Comment by semiosis** [comment]
Some of the related keywords are missing from custom_related.json.  Most notably, shit.

**Comment by JYZR** [comment]
👍

**Comment by jalada** [comment]
I refreshed this again: https://github.com/jalada/alfred-emoji-workflow

**Comment by kbrock** [comment]
Great PR - a little on the big side, though.

@carlosgaldino do you like the idea of using `JSON` instead of a ruby hash?

Maybe split up the PR a bit:

1. the scripts
2. conversion of the current files over to json
3. the new emoji

Suggestion: don't split it up unless @carlosgaldino likes the idea/gives a :+1:

**Comment by carlosgaldino** [comment]
This project is being archived.

**Pull request closed without merging**
