### PR TITLE
Add USA keyword for searching US flag

### PR DESCRIPTION
**Pull request by iansinnott**
**Reason for the PR**

I sometimes found myself typing "usa" when I was looking for the american flag emoji. 

**What I Changed**

I added a few more keywords to `related_words.rb`.

### CODE REVIEW

**Comment by retornam** [comment]
@iansinnott there is already a ```USA`` keyword under ```earth_americas' => ['globe', 'world', 'USA', 'international'],```

**Comment by iansinnott** [comment]
Yes, but keywords are not one-to-one relationships. Many different emoji can share some of the same keywords. 

For example, in the current version when you type "usa" it displays the globe as the only search result. With the addition of this keyword it would display the globe _and_ the flag.

**Comment by carlosgaldino** [comment]
Thanks. I suggest you to download the latest package which includes this update.

**Comment by iansinnott** [comment]
Cheers, thanks @carlosgaldino

**Pull request merged**
