### PR TITLE
Added thinking_face symbol

### PR DESCRIPTION
**Pull request by dgmltn**

### CODE REVIEW

**Comment by jsumners** [comment]
@dgmltn maybe add 'thinking' to the keyword match list?

**Comment by dgmltn** [comment]
@jsumners I don't think that's necessary; any partial search that would partially match "thinking" (like "thinki") would also partially match "thinking_face". Do you have an example use case where that's not true?

FWIW, I used "thinking_face" because it's the name used by Slack.

**Comment by jsumners** [comment]
I don't know. I was just looking at the patch and noticed the only alias is "hmmm".

**Comment by matthewwithanm** [comment]
@carlosgaldino Are you still maintaining this? It's such an important part of my workflow but it's missing newer emoji 😊

**Comment by jsumners** [comment]
Guys, try https://github.com/jsumners/alfred-emoji

**Comment by dgmltn** [comment]
stale

**Pull request closed without merging**
