### PR TITLE
Add Fitzpatrick scale unicode characters to emoji list

### PR DESCRIPTION
**Pull request by breestanwyck**
This adds unicode characters for the Fitzpatrick scale skin tones to the workflow as `skin{12,3,4,5,6}`.

### CODE REVIEW

**Comment by pwnela** [comment]
:+1:

**Comment by carlosgaldino** [comment]
This is just a square with different colors?

**Comment by breestanwyck** [comment]
They're modifiers that change the skin-tone on certain emojis: http://mashable.com/2015/02/26/diverse-emoji-explainer/

**Comment by carlosgaldino** [comment]
Cool. Just added on f7fb03fc3824097a99eef5b630b596b12bfe63b9.

Thank you.

**Pull request closed without merging**
